-- ============================================================
--  TOQA - QR dinamicos
--  Ejecutar entero en Supabase > SQL Editor (es idempotente).
-- ============================================================

-- ------------------------------------------------------------
-- 1. Tablas principales
-- ------------------------------------------------------------

create table if not exists public.qr_codes (
  id              bigint generated by default as identity primary key,
  label           text,
  destination_url text not null,
  created_at      timestamptz not null default now()
);

create table if not exists public.scans (
  id         bigint generated by default as identity primary key,
  qr_id      bigint not null references public.qr_codes (id) on delete cascade,
  scanned_at timestamptz not null default now(),
  user_agent text
);

create index if not exists scans_qr_id_scanned_at_idx
  on public.scans (qr_id, scanned_at desc);

-- ------------------------------------------------------------
-- 2. Integracion con Canva Connect (opcional)
-- ------------------------------------------------------------

create table if not exists public.canva_connections (
  id            int primary key default 1 check (id = 1),
  access_token  text        not null,
  refresh_token text        not null,
  expires_at    timestamptz not null,
  scopes        text,
  updated_at    timestamptz not null default now()
);

create table if not exists public.canva_batches (
  id                bigint generated by default as identity primary key,
  brand_template_id text not null,
  status            text not null default 'running',  -- running | done | error
  error             text,
  created_at        timestamptz not null default now()
);

create table if not exists public.canva_batch_items (
  id         bigint generated by default as identity primary key,
  batch_id   bigint not null references public.canva_batches (id) on delete cascade,
  qr_id      bigint not null references public.qr_codes (id) on delete cascade,
  status     text   not null default 'pending',  -- pending | asset | design | done | error
  asset_id   text,
  design_id  text,
  export_url text,
  error      text,
  updated_at timestamptz not null default now()
);

create index if not exists canva_batch_items_batch_idx
  on public.canva_batch_items (batch_id, status);

-- ------------------------------------------------------------
-- 3. Vista con estadisticas para el listado del dashboard
-- ------------------------------------------------------------

create or replace view public.qr_codes_with_stats
with (security_invoker = true) as
  select
    q.id,
    q.label,
    q.destination_url,
    q.created_at,
    count(s.id)::bigint as total_scans,
    max(s.scanned_at)   as last_scan_at
  from public.qr_codes q
  left join public.scans s on s.qr_id = q.id
  group by q.id, q.label, q.destination_url, q.created_at;

-- ------------------------------------------------------------
-- 4. Resolucion publica del QR: registra el scan y devuelve el destino
--    (SECURITY DEFINER: el visitante anonimo no toca las tablas directo)
-- ------------------------------------------------------------

create or replace function public.resolve_qr(p_id bigint, p_user_agent text default null)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_url text;
begin
  select destination_url into v_url from public.qr_codes where id = p_id;

  if v_url is null then
    return null;
  end if;

  insert into public.scans (qr_id, user_agent) values (p_id, left(p_user_agent, 500));

  return v_url;
end;
$$;

revoke all on function public.resolve_qr(bigint, text) from public;
grant execute on function public.resolve_qr(bigint, text) to anon, authenticated;

-- ------------------------------------------------------------
-- 5. Serie temporal de escaneos (dia / semana / mes) sin huecos
-- ------------------------------------------------------------

create or replace function public.qr_scan_series(
  p_qr_id  bigint,
  p_bucket text,
  p_from   timestamptz,
  p_tz     text default 'America/Argentina/Buenos_Aires'
)
returns table (bucket_start timestamp, scans bigint)
language plpgsql
stable
security definer
set search_path = public
as $$
-- Los nombres de OUT (bucket_start, scans) chocan con la tabla scans y sus
-- columnas; que gane siempre la columna.
#variable_conflict use_column
begin
  if p_bucket not in ('day', 'week', 'month') then
    raise exception 'bucket invalido: %', p_bucket;
  end if;

  return query
  with buckets as (
    select generate_series(
      date_trunc(p_bucket, p_from at time zone p_tz),
      date_trunc(p_bucket, now()   at time zone p_tz),
      ('1 ' || p_bucket)::interval
    ) as bucket_start
  )
  select b.bucket_start,
         count(s.id)::bigint
  from buckets b
  left join public.scans s
    on s.qr_id = p_qr_id
   and date_trunc(p_bucket, s.scanned_at at time zone p_tz) = b.bucket_start
  group by b.bucket_start
  order by b.bucket_start;
end;
$$;

revoke all on function public.qr_scan_series(bigint, text, timestamptz, text) from public;
grant execute on function public.qr_scan_series(bigint, text, timestamptz, text) to authenticated;

-- ------------------------------------------------------------
-- 6. Migracion: despues de importar IDs explicitos hay que
--    reposicionar la secuencia para que los nuevos QR no choquen.
-- ------------------------------------------------------------

create or replace function public.sync_qr_id_sequence()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_max bigint;
begin
  select coalesce(max(id), 0) into v_max from public.qr_codes;
  perform setval(pg_get_serial_sequence('public.qr_codes', 'id'), greatest(v_max, 1), v_max > 0);
  return v_max;
end;
$$;

revoke all on function public.sync_qr_id_sequence() from public;
grant execute on function public.sync_qr_id_sequence() to authenticated;

-- ------------------------------------------------------------
-- 7. RLS: nadie lee las tablas sin estar logueado.
--    El visitante del QR pasa unicamente por resolve_qr().
-- ------------------------------------------------------------

alter table public.qr_codes         enable row level security;
alter table public.scans            enable row level security;
alter table public.canva_connections enable row level security;
alter table public.canva_batches     enable row level security;
alter table public.canva_batch_items enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array[
    'qr_codes', 'scans', 'canva_connections', 'canva_batches', 'canva_batch_items'
  ] loop
    execute format('drop policy if exists %I on public.%I', t || '_admin_all', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (true) with check (true)',
      t || '_admin_all', t
    );
  end loop;
end;
$$;

-- ------------------------------------------------------------
-- 8. Permisos de tabla.
--    Supabase ya suele otorgarlos por defecto, pero dejarlos escritos
--    hace que el esquema funcione igual en cualquier proyecto.
--    anon no recibe nada: su unica puerta es resolve_qr().
-- ------------------------------------------------------------

grant usage on schema public to anon, authenticated;

do $$
declare
  t text;
begin
  foreach t in array array[
    'qr_codes', 'scans', 'canva_connections', 'canva_batches', 'canva_batch_items'
  ] loop
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end;
$$;

revoke all on public.qr_codes_with_stats from anon;
grant select on public.qr_codes_with_stats to authenticated;

-- Las columnas identity no necesitan grant de secuencia, pero si alguien
-- migra a serial esto evita un "permission denied for sequence".
grant usage, select on all sequences in schema public to authenticated;

-- ------------------------------------------------------------
-- 9. Placas para imprenta.
--    Guarda el fondo exportado de Canva (PDF vectorial, en base64) y
--    la posicion del QR sobre el. Asi el diseno se cambia desde el panel
--    y nunca hace falta tocar codigo ni volver a desplegar.
-- ------------------------------------------------------------

create table if not exists public.placa_settings (
  id             int primary key default 1 check (id = 1),
  background_pdf text,           -- PDF de fondo, base64
  background_name text,
  layout         jsonb not null default '{
    "qrPage": 1,
    "xMm": 30,
    "yMm": 120,
    "sizeMm": 40,
    "quietModules": 2,
    "whiteBackdrop": true
  }'::jsonb,
  updated_at     timestamptz not null default now()
);

insert into public.placa_settings (id) values (1) on conflict (id) do nothing;

alter table public.placa_settings enable row level security;

drop policy if exists placa_settings_admin_all on public.placa_settings;
create policy placa_settings_admin_all on public.placa_settings
  for all to authenticated using (true) with check (true);

revoke all on public.placa_settings from anon;
grant select, insert, update, delete on public.placa_settings to authenticated;
