-- ------------------------------------------------------------------
-- Bot de WhatsApp: un menú al empezar cada conversación, y el reporte de
-- estadísticas para los clientes.
--
-- Pegá TODO esto en Supabase → SQL Editor → Run. Se puede correr más de una
-- vez. No borra nada y no cambia ningún QR.
--
-- Requiere haber corrido antes 2026-10-clientes.sql.
--
-- Cómo funciona:
--   - El bot corre en el sitio, sin nadie logueado. Para leer la base usa
--     una llave propia: el dueño la genera en el panel (WhatsApp → Generar
--     llave) y la pega en Vercel. La base guarda solo una huella de la
--     llave, nunca la llave.
--   - Con la llave, el bot puede solamente: anotar un mensaje recibido,
--     recordar que espera unas fechas o que tiene que quedarse callado con
--     un número, leer sus textos, y leer las estadísticas de las placas del
--     cliente dueño del teléfono que escribió. No ve otros clientes ni
--     cambia nada más.
--   - Los textos que manda el bot los edita el dueño en el panel.
--   - Sin la llave, esas funciones no hacen nada. No se usa la clave
--     secreta de Supabase.
-- ------------------------------------------------------------------

-- 1. La huella de la llave (una sola fila).
create table if not exists public.bot_config (
  id          integer primary key default 1 check (id = 1),
  llave_hash  text not null,
  creada_en   timestamptz not null default now()
);

-- 2. Los mensajes que ya se atendieron (Meta a veces manda el mismo dos
--    veces) y lo que el bot espera de cada teléfono.
create table if not exists public.bot_mensajes (
  wamid      text primary key,
  telefono   text not null,
  recibido_en timestamptz not null default now()
);

create table if not exists public.bot_esperas (
  telefono text primary key,
  espera   text not null,
  hasta    timestamptz not null
);

-- 3. Las consultas, para verlas en el panel.
create table if not exists public.bot_consultas (
  id          bigint generated by default as identity primary key,
  telefono    text not null,
  clientes    text,
  desde       date,
  hasta       date,
  resultado   text not null,
  creado_en   timestamptz not null default now()
);

create index if not exists bot_consultas_por_fecha on public.bot_consultas (creado_en desc);

-- Con qué números el bot se queda callado, porque sigue una persona.
create table if not exists public.bot_silencios (
  telefono text primary key,
  hasta    timestamptz not null
);

-- Los textos del bot que el dueño cambió (los que no están acá usan el
-- texto de siempre).
create table if not exists public.bot_textos (
  clave          text primary key,
  texto          text not null check (length(texto) between 1 and 1000),
  actualizado_en timestamptz not null default now()
);

-- Nadie las lee ni las escribe directo, salvo el dueño, que mira las
-- consultas y edita los textos. Todo lo demás pasa por las funciones de
-- abajo.
alter table public.bot_silencios enable row level security;
alter table public.bot_textos enable row level security;
alter table public.bot_config enable row level security;
alter table public.bot_mensajes enable row level security;
alter table public.bot_esperas enable row level security;
alter table public.bot_consultas enable row level security;

revoke all on public.bot_config, public.bot_mensajes, public.bot_esperas, public.bot_consultas,
  public.bot_silencios, public.bot_textos
  from anon, authenticated;

drop policy if exists bot_textos_dueno on public.bot_textos;
create policy bot_textos_dueno on public.bot_textos
  for all to authenticated using (public.es_dueno()) with check (public.es_dueno());
grant select, insert, update, delete on public.bot_textos to authenticated;

drop policy if exists bot_consultas_leer on public.bot_consultas;
create policy bot_consultas_leer on public.bot_consultas
  for select to authenticated using (public.es_dueno());
grant select on public.bot_consultas to authenticated;

-- 4. La llave.
--    WhatsApp manda los números de Argentina con el 9 (549…) y a veces sin
--    él: se comparan sin el 9 para que coincidan igual.
create or replace function public.bot_telefono_comparable(p_telefono text)
returns text
language sql
immutable
as $$
  select regexp_replace(regexp_replace(coalesce(p_telefono, ''), '\D', '', 'g'), '^549', '54');
$$;

create or replace function public.bot_llave_valida(p_llave text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(length(p_llave) >= 32, false) and exists (
    select 1 from public.bot_config
    where id = 1 and llave_hash = encode(sha256(convert_to(p_llave, 'UTF8')), 'hex')
  );
$$;

revoke all on function public.bot_llave_valida(text) from public;
grant execute on function public.bot_llave_valida(text) to anon, authenticated;

-- Solo el dueño. Devuelve la llave nueva una única vez; la anterior deja
-- de servir en el acto.
create or replace function public.bot_generar_llave()
returns text
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_llave text;
begin
  if not public.es_dueno() then
    raise exception 'Solo el dueño puede generar la llave del bot';
  end if;
  v_llave := replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');
  insert into public.bot_config (id, llave_hash, creada_en)
  values (1, encode(sha256(convert_to(v_llave, 'UTF8')), 'hex'), now())
  on conflict (id) do update set llave_hash = excluded.llave_hash, creada_en = excluded.creada_en;
  return v_llave;
end;
$$;

revoke all on function public.bot_generar_llave() from public;
grant execute on function public.bot_generar_llave() to authenticated;

-- 5. Llega un mensaje: se anota (si ya estaba, es repetido) y se devuelve
--    todo lo que el bot necesita para decidir: de qué clientes es el
--    teléfono, si es una conversación nueva (no escribía hace 12 horas), si
--    tiene que quedarse callado, si esperaba algo, y sus textos.
create or replace function public.bot_recibir(p_llave text, p_wamid text, p_telefono text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_tel     text := public.bot_telefono_comparable(p_telefono);
  v_filas   integer;
  v_ultimo  timestamptz;
  v_espera  text;
  v_nombres text[];
  v_textos  jsonb;
begin
  if not public.bot_llave_valida(p_llave) then
    raise exception 'Llave del bot inválida';
  end if;

  delete from public.bot_mensajes where recibido_en < now() - interval '7 days';
  delete from public.bot_esperas where hasta < now();
  delete from public.bot_silencios where hasta < now();

  select max(m.recibido_en) into v_ultimo from public.bot_mensajes m
  where public.bot_telefono_comparable(m.telefono) = v_tel and m.wamid <> p_wamid;

  insert into public.bot_mensajes (wamid, telefono) values (left(p_wamid, 200), left(v_tel, 20))
  on conflict (wamid) do nothing;
  get diagnostics v_filas = row_count;

  select e.espera into v_espera from public.bot_esperas e where e.telefono = v_tel and e.hasta >= now();

  select array_agg(distinct c.nombre order by c.nombre) into v_nombres
  from public.clientes c
  join public.cliente_telefonos t on t.cliente_id = c.id
  where public.bot_telefono_comparable(t.telefono) = v_tel;

  select jsonb_object_agg(clave, texto) into v_textos from public.bot_textos;

  return jsonb_build_object(
    'nuevo', v_filas > 0,
    'conversacion_nueva', v_ultimo is null or v_ultimo < now() - interval '12 hours',
    'silencio', exists (select 1 from public.bot_silencios s where s.telefono = v_tel and s.hasta >= now()),
    'espera', v_espera,
    'clientes', coalesce(to_jsonb(v_nombres), '[]'::jsonb),
    'textos', coalesce(v_textos, '{}'::jsonb)
  );
end;
$$;

revoke all on function public.bot_recibir(text, text, text) from public;
grant execute on function public.bot_recibir(text, text, text) to anon, authenticated;

-- 6. Recordar (o olvidar, con p_espera vacío) que el bot espera algo de un
--    teléfono, por ejemplo las fechas. Vence sola a los 15 minutos.
create or replace function public.bot_esperar(p_llave text, p_telefono text, p_espera text)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
begin
  if not public.bot_llave_valida(p_llave) then
    raise exception 'Llave del bot inválida';
  end if;
  if coalesce(p_espera, '') = '' then
    delete from public.bot_esperas where telefono = public.bot_telefono_comparable(p_telefono);
  else
    insert into public.bot_esperas (telefono, espera, hasta)
    values (public.bot_telefono_comparable(p_telefono), left(p_espera, 40), now() + interval '15 minutes')
    on conflict (telefono) do update set espera = excluded.espera, hasta = excluded.hasta;
  end if;
end;
$$;

revoke all on function public.bot_esperar(text, text, text) from public;
grant execute on function public.bot_esperar(text, text, text) to anon, authenticated;

-- 6b. Quedarse callado con un número por unas horas (0: volver a hablar),
--     porque la charla la sigue una persona.
create or replace function public.bot_silenciar(p_llave text, p_telefono text, p_horas integer)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
begin
  if not public.bot_llave_valida(p_llave) then
    raise exception 'Llave del bot inválida';
  end if;
  if coalesce(p_horas, 0) <= 0 then
    delete from public.bot_silencios where telefono = public.bot_telefono_comparable(p_telefono);
  else
    insert into public.bot_silencios (telefono, hasta)
    values (public.bot_telefono_comparable(p_telefono), now() + make_interval(hours => least(p_horas, 72)))
    on conflict (telefono) do update set hasta = excluded.hasta;
  end if;
end;
$$;

revoke all on function public.bot_silenciar(text, text, integer) from public;
grant execute on function public.bot_silenciar(text, text, integer) to anon, authenticated;

-- 7. Anotar una consulta (también las de números que no son clientes).
create or replace function public.bot_anotar(
  p_llave text, p_telefono text, p_clientes text, p_desde date, p_hasta date, p_resultado text
)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
begin
  if not public.bot_llave_valida(p_llave) then
    raise exception 'Llave del bot inválida';
  end if;
  insert into public.bot_consultas (telefono, clientes, desde, hasta, resultado)
  values (left(p_telefono, 20), left(p_clientes, 300), p_desde, p_hasta, left(p_resultado, 40));
end;
$$;

revoke all on function public.bot_anotar(text, text, text, date, date, text) from public;
grant execute on function public.bot_anotar(text, text, text, date, date, text) to anon, authenticated;

-- 8. Las estadísticas de las placas de los clientes de ese teléfono: una
--    fila por placa y por tramo (día, semana, mes o año), separadas en QR y
--    NFC, con la misma cuenta que el gráfico del panel.
create or replace function public.bot_estadisticas(
  p_llave    text,
  p_telefono text,
  p_desde    date,
  p_hasta    date,
  p_bucket   text,
  p_tz       text default 'America/Argentina/Buenos_Aires'
)
returns table (qr_id bigint, label text, cliente text, bucket_start timestamp, qr bigint, nfc bigint)
language plpgsql
stable
security definer
set search_path = public
as $$
#variable_conflict use_column
begin
  if not public.bot_llave_valida(p_llave) then
    raise exception 'Llave del bot inválida';
  end if;
  if p_bucket not in ('day', 'week', 'month', 'year') then
    raise exception 'bucket invalido: %', p_bucket;
  end if;
  if p_hasta < p_desde or p_hasta - p_desde > 3660 then
    raise exception 'rango invalido';
  end if;

  return query
  with placas as (
    select distinct q.id, q.label, c.nombre
    from public.qr_codes q
    join public.clientes c on c.id = q.cliente_id
    join public.cliente_telefonos t on t.cliente_id = c.id
    where public.bot_telefono_comparable(t.telefono) = public.bot_telefono_comparable(p_telefono)
  ),
  tramos as (
    select generate_series(
      date_trunc(p_bucket, p_desde::timestamp),
      date_trunc(p_bucket, p_hasta::timestamp),
      ('1 ' || p_bucket)::interval
    ) as bucket_start
  )
  select p.id, p.label, p.nombre, t.bucket_start,
         (count(s.id) filter (where s.via is distinct from 'nfc'))::bigint,
         (count(s.id) filter (where s.via = 'nfc'))::bigint
  from placas p
  cross join tramos t
  left join public.scans s
    on s.qr_id = p.id
   and (s.scanned_at at time zone p_tz) >= p_desde::timestamp
   and (s.scanned_at at time zone p_tz) <  (p_hasta + 1)::timestamp
   and date_trunc(p_bucket, s.scanned_at at time zone p_tz) = t.bucket_start
  group by p.id, p.label, p.nombre, t.bucket_start
  order by p.id, t.bucket_start;
end;
$$;

revoke all on function public.bot_estadisticas(text, text, date, date, text, text) from public;
grant execute on function public.bot_estadisticas(text, text, date, date, text, text) to anon, authenticated;
