-- ------------------------------------------------------------------
-- Clientes: de quién es cada placa.
--
-- Pegá TODO esto en Supabase → SQL Editor → Run. Se puede correr más de una
-- vez. No borra nada y no cambia ningún QR.
--
-- Requiere haber corrido antes 2026-10-historial.sql y 2026-10-papelera.sql.
--
-- Cómo funciona:
--   - Cada cliente tiene su nombre (el del negocio), una persona de
--     contacto, uno o más teléfonos de WhatsApp y notas.
--   - Cada placa puede ser de un cliente, o de ninguno.
--   - Lo ven y lo editan el dueño y el equipo. Borrar un cliente, solo el
--     dueño: sus placas no se tocan, quedan sin cliente.
--   - El historial anota cuando una placa cambia de cliente, y la papelera
--     la devuelve con su cliente.
-- ------------------------------------------------------------------

-- 1. Las tablas.
create table if not exists public.clientes (
  id        bigint generated by default as identity primary key,
  nombre    text not null check (length(btrim(nombre)) > 0),
  contacto  text,
  notas     text,
  creado_en timestamptz not null default now()
);

-- Los teléfonos van solo con números y con el código de país
-- (5491112345678): así se los puede comparar con el que informa WhatsApp.
create table if not exists public.cliente_telefonos (
  cliente_id bigint not null references public.clientes (id) on delete cascade,
  telefono   text not null check (telefono ~ '^[0-9]{8,15}$'),
  primary key (cliente_id, telefono)
);

create index if not exists cliente_telefonos_por_numero on public.cliente_telefonos (telefono);

alter table public.qr_codes
  add column if not exists cliente_id bigint references public.clientes (id) on delete set null;

create index if not exists qr_codes_por_cliente on public.qr_codes (cliente_id);

-- 2. Permisos: como las placas. Mirar, crear y editar, cualquiera con
--    acceso; borrar, solo el dueño.
alter table public.clientes enable row level security;
alter table public.cliente_telefonos enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array['clientes', 'cliente_telefonos'] loop
    execute format('drop policy if exists %I on public.%I', t || '_leer', t);
    execute format('drop policy if exists %I on public.%I', t || '_crear', t);
    execute format('drop policy if exists %I on public.%I', t || '_editar', t);
    execute format('drop policy if exists %I on public.%I', t || '_borrar', t);
    execute format('create policy %I on public.%I for select to authenticated using (public.es_miembro())',
      t || '_leer', t);
    execute format('create policy %I on public.%I for insert to authenticated with check (public.es_miembro())',
      t || '_crear', t);
    execute format('create policy %I on public.%I for update to authenticated using (public.es_miembro()) with check (public.es_miembro())',
      t || '_editar', t);
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end;
$$;

create policy clientes_borrar on public.clientes
  for delete to authenticated using (public.es_dueno());

-- Un teléfono sí lo puede sacar cualquiera del equipo: es editar el cliente.
create policy cliente_telefonos_borrar on public.cliente_telefonos
  for delete to authenticated using (public.es_miembro());

-- 3. La lista de QRs muestra el cliente de cada placa. Las columnas nuevas
--    van al final para poder reemplazar la vista sin borrarla.
create or replace view public.qr_codes_with_stats
with (security_invoker = true) as
  select
    q.id,
    q.label,
    q.destination_url,
    q.created_at,
    q.design_id,
    d.name              as design_name,
    count(s.id)::bigint as total_scans,
    max(s.scanned_at)   as last_scan_at,
    q.cliente_id,
    c.nombre            as cliente_nombre
  from public.qr_codes q
  left join public.scans s on s.qr_id = q.id
  left join public.placa_designs d on d.id = q.design_id
  left join public.clientes c on c.id = q.cliente_id
  group by q.id, q.label, q.destination_url, q.created_at, q.design_id, d.name, q.cliente_id, c.nombre;

revoke all on public.qr_codes_with_stats from anon;
grant select on public.qr_codes_with_stats to authenticated;

-- 4. El historial anota también los cambios de cliente.
create or replace function public.anotar_cambio_qr()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid     uuid := auth.uid();
  v_email   text;
  v_cambios jsonb := '{}'::jsonb;
begin
  select email into v_email from public.perfiles where id = v_uid;

  if tg_op = 'INSERT' then
    insert into public.historial (qr_id, accion, cambios, usuario_id, usuario_email)
    values (
      new.id,
      case when current_setting('toqa.recuperando', true) = 'si' then 'recupero' else 'creo' end,
      jsonb_strip_nulls(jsonb_build_object(
        'destino', jsonb_build_object('despues', new.destination_url),
        'etiqueta', case when new.label is not null then jsonb_build_object('despues', new.label) end,
        'diseno', case when new.design_id is not null then jsonb_build_object(
          'despues', (select name from public.placa_designs where id = new.design_id)) end,
        'cliente', case when new.cliente_id is not null then jsonb_build_object(
          'despues', (select nombre from public.clientes where id = new.cliente_id)) end
      )),
      v_uid,
      v_email
    );
    return new;
  end if;

  if tg_op = 'DELETE' then
    insert into public.historial (qr_id, accion, cambios, usuario_id, usuario_email)
    values (
      old.id,
      'borro',
      jsonb_strip_nulls(jsonb_build_object(
        'destino', jsonb_build_object('antes', old.destination_url),
        'etiqueta', case when old.label is not null then jsonb_build_object('antes', old.label) end
      )),
      v_uid,
      v_email
    );
    return old;
  end if;

  if new.destination_url is distinct from old.destination_url then
    v_cambios := v_cambios || jsonb_build_object('destino',
      jsonb_build_object('antes', old.destination_url, 'despues', new.destination_url));
  end if;
  if new.label is distinct from old.label then
    v_cambios := v_cambios || jsonb_build_object('etiqueta',
      jsonb_build_object('antes', old.label, 'despues', new.label));
  end if;
  if new.design_id is distinct from old.design_id then
    v_cambios := v_cambios || jsonb_build_object('diseno', jsonb_build_object(
      'antes', case when old.design_id is not null then coalesce(
        (select name from public.placa_designs where id = old.design_id), 'un diseño ya borrado') end,
      'despues', case when new.design_id is not null then coalesce(
        (select name from public.placa_designs where id = new.design_id), 'un diseño ya borrado') end));
  end if;
  if new.cliente_id is distinct from old.cliente_id then
    v_cambios := v_cambios || jsonb_build_object('cliente', jsonb_build_object(
      'antes', case when old.cliente_id is not null then coalesce(
        (select nombre from public.clientes where id = old.cliente_id), 'un cliente ya borrado') end,
      'despues', case when new.cliente_id is not null then coalesce(
        (select nombre from public.clientes where id = new.cliente_id), 'un cliente ya borrado') end));
  end if;

  if v_cambios <> '{}'::jsonb then
    insert into public.historial (qr_id, accion, cambios, usuario_id, usuario_email)
    values (new.id, 'edito', v_cambios, v_uid, v_email);
  end if;
  return new;
end;
$$;

-- 5. La papelera guarda y devuelve el cliente.
alter table public.papelera add column if not exists cliente_id bigint;
alter table public.papelera add column if not exists cliente_nombre text;

create or replace function public.guardar_en_papelera()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  perform public.vaciar_papelera();

  delete from public.papelera where qr_id = old.id;

  insert into public.papelera (
    qr_id, label, destination_url, created_at, design_id, diseno_nombre,
    cliente_id, cliente_nombre, borrado_por_id, borrado_por_email
  )
  values (
    old.id, old.label, old.destination_url, old.created_at, old.design_id,
    (select name from public.placa_designs where id = old.design_id),
    old.cliente_id, (select nombre from public.clientes where id = old.cliente_id),
    v_uid, (select email from public.perfiles where id = v_uid)
  );

  insert into public.papelera_escaneos (id, qr_id, scanned_at, user_agent, via)
  select s.id, s.qr_id, s.scanned_at, s.user_agent, s.via
  from public.scans s
  where s.qr_id = old.id;

  return old;
end;
$$;

create or replace function public.recuperar_placas(p_ids bigint[])
returns table (qr_id bigint, resultado text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_p  public.papelera%rowtype;
begin
  if not public.es_dueno() then
    raise exception 'Solo el dueño puede recuperar placas';
  end if;

  perform public.vaciar_papelera();

  foreach v_id in array coalesce(p_ids[1:1000], '{}') loop
    select * into v_p from public.papelera p where p.qr_id = v_id;

    if not found then
      qr_id := v_id; resultado := 'no-esta'; return next; continue;
    end if;
    if exists (select 1 from public.qr_codes q where q.id = v_id) then
      qr_id := v_id; resultado := 'en-uso'; return next; continue;
    end if;

    perform set_config('toqa.recuperando', 'si', true);
    insert into public.qr_codes (id, label, destination_url, created_at, design_id, cliente_id)
    values (
      v_p.qr_id, v_p.label, v_p.destination_url, v_p.created_at,
      (select d.id from public.placa_designs d where d.id = v_p.design_id),
      (select c.id from public.clientes c where c.id = v_p.cliente_id)
    );
    perform set_config('toqa.recuperando', '', true);

    insert into public.scans (id, qr_id, scanned_at, user_agent, via)
    select e.id, e.qr_id, e.scanned_at, e.user_agent, e.via
    from public.papelera_escaneos e
    where e.qr_id = v_id;

    delete from public.papelera p where p.qr_id = v_id;

    qr_id := v_id; resultado := 'ok'; return next;
  end loop;
end;
$$;

revoke all on function public.recuperar_placas(bigint[]) from public;
grant execute on function public.recuperar_placas(bigint[]) to authenticated;
