-- ------------------------------------------------------------------
-- Historial: quién hizo qué con cada placa, y cuándo.
--
-- Pegá TODO esto en Supabase → SQL Editor → Run. Se puede correr más de una
-- vez. No borra nada y no cambia ningún QR.
--
-- Requiere haber corrido antes 2026-10-acceso-aprobado.sql.
--
-- Cómo funciona:
--   - Lo anota la base sola, cada vez que una placa se crea, cambia o se
--     borra, venga el cambio de donde venga: el panel, una importación de
--     CSV o alguien que intente saltearse el panel.
--   - Las impresiones las anota el panel al generar el PDF, pero quién
--     imprimió lo pone la base: nadie puede anotar a nombre de otro.
--   - Nadie lo puede modificar ni borrar desde el panel, ni el dueño. Solo el
--     dueño lo puede leer.
--   - Lo previo a esta migración no se puede reconstruir: el historial
--     empieza el día que se corre.
-- ------------------------------------------------------------------

-- 1. La tabla. Sin referencia a qr_codes a propósito: si una placa se borra,
--    su historia tiene que quedar.
create table if not exists public.historial (
  id            bigint generated by default as identity primary key,
  qr_id         bigint,
  accion        text not null,
  cambios       jsonb not null default '{}'::jsonb,
  detalle       jsonb not null default '{}'::jsonb,
  usuario_id    uuid,
  usuario_email text,
  creado_en     timestamptz not null default now()
);

do $$
begin
  alter table public.historial
    add constraint historial_accion_check check (accion in ('creo', 'edito', 'borro', 'imprimio'));
exception
  when duplicate_object then null;
end;
$$;

create index if not exists historial_por_placa on public.historial (qr_id, creado_en desc);
create index if not exists historial_por_fecha on public.historial (creado_en desc);

-- 2. Permisos: el dueño lee, nadie escribe directo. Sin politicas de
--    insert, update ni delete, y sin esos permisos: solo escriben las
--    funciones de abajo, que corren con permisos propios.
alter table public.historial enable row level security;

drop policy if exists historial_leer on public.historial;
create policy historial_leer on public.historial
  for select to authenticated using (public.es_dueno());

revoke all on public.historial from anon, authenticated;
grant select on public.historial to authenticated;

-- 3. La cámara: anota cada alta, cambio y baja de una placa.
create or replace function public.anotar_cambio_qr()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid     uuid := auth.uid();
  v_email   text;
  v_cambios jsonb := '{}'::jsonb;
begin
  -- Sin usuario (por ejemplo, un cambio hecho a mano en Supabase) queda
  -- anotado igual, sin nombre: el panel lo muestra como "Sistema".
  select email into v_email from public.perfiles where id = v_uid;

  if tg_op = 'INSERT' then
    insert into public.historial (qr_id, accion, cambios, usuario_id, usuario_email)
    values (
      new.id,
      'creo',
      jsonb_strip_nulls(jsonb_build_object(
        'destino', jsonb_build_object('despues', new.destination_url),
        'etiqueta', case when new.label is not null then jsonb_build_object('despues', new.label) end,
        'diseno', case when new.design_id is not null then jsonb_build_object(
          'despues', (select name from public.placa_designs where id = new.design_id)) end
      )),
      v_uid,
      v_email
    );
    return new;
  end if;

  if tg_op = 'DELETE' then
    insert into public.historial (qr_id, accion, cambios, usuario_id, usuario_email)
    values (
      old.id,
      'borro',
      jsonb_strip_nulls(jsonb_build_object(
        'destino', jsonb_build_object('antes', old.destination_url),
        'etiqueta', case when old.label is not null then jsonb_build_object('antes', old.label) end
      )),
      v_uid,
      v_email
    );
    return old;
  end if;

  -- UPDATE: solo lo que de verdad cambió. Si no cambió nada (una
  -- importación que reescribe lo mismo), no se anota nada.
  if new.destination_url is distinct from old.destination_url then
    v_cambios := v_cambios || jsonb_build_object('destino',
      jsonb_build_object('antes', old.destination_url, 'despues', new.destination_url));
  end if;
  if new.label is distinct from old.label then
    v_cambios := v_cambios || jsonb_build_object('etiqueta',
      jsonb_build_object('antes', old.label, 'despues', new.label));
  end if;
  if new.design_id is distinct from old.design_id then
    -- Si el cambio es porque se borró el diseño, para este momento ya no
    -- existe y no se le encuentra el nombre: se dice eso en vez de nada.
    v_cambios := v_cambios || jsonb_build_object('diseno', jsonb_build_object(
      'antes', case when old.design_id is not null then coalesce(
        (select name from public.placa_designs where id = old.design_id), 'un diseño ya borrado') end,
      'despues', case when new.design_id is not null then coalesce(
        (select name from public.placa_designs where id = new.design_id), 'un diseño ya borrado') end));
  end if;

  if v_cambios <> '{}'::jsonb then
    insert into public.historial (qr_id, accion, cambios, usuario_id, usuario_email)
    values (new.id, 'edito', v_cambios, v_uid, v_email);
  end if;
  return new;
end;
$$;

drop trigger if exists anotar_cambio_qr on public.qr_codes;
create trigger anotar_cambio_qr
  after insert or update or delete on public.qr_codes
  for each row execute function public.anotar_cambio_qr();

-- 4. Las impresiones. Quién imprimió lo pone la base, no quien llama.
create or replace function public.registrar_impresion(
  p_ids     bigint[],
  p_disenos text[],
  p_formato text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid   uuid := auth.uid();
  v_email text;
begin
  if not public.es_miembro() then
    raise exception 'Sin permiso para registrar impresiones';
  end if;
  select email into v_email from public.perfiles where id = v_uid;

  insert into public.historial (qr_id, accion, detalle, usuario_id, usuario_email)
  select t.id, 'imprimio', jsonb_strip_nulls(jsonb_build_object('diseno', t.diseno, 'formato', p_formato)), v_uid, v_email
  from unnest(p_ids[1:1000], p_disenos[1:1000]) as t(id, diseno)
  where t.id is not null;
end;
$$;

revoke all on function public.registrar_impresion(bigint[], text[], text) from public;
grant execute on function public.registrar_impresion(bigint[], text[], text) to authenticated;

-- 5. La lista general: agrupa lo que se hizo de una sola vez (crear 100
--    placas, imprimir un lote, borrar varias), que comparte el mismo
--    instante, para que se lea un renglón por acción y no cien.
--    Corre con los permisos de quien la llama: solo el dueño ve algo.
create or replace function public.historial_general(
  p_limite  integer default 100,
  p_antes   timestamptz default null,
  p_qr      bigint default null,
  p_usuario text default null
)
returns table (
  accion        text,
  usuario_email text,
  creado_en     timestamptz,
  cantidad      bigint,
  desde_qr      bigint,
  hasta_qr      bigint,
  cambios       jsonb,
  campos        text[],
  disenos       text[],
  formato       text
)
language sql
stable
set search_path = public
as $$
  with grupos as (
    select h.accion, h.usuario_id, h.usuario_email, h.creado_en,
           count(*) as cantidad,
           min(h.qr_id) as desde_qr,
           max(h.qr_id) as hasta_qr,
           array_agg(h.cambios) as todos_cambios,
           array_agg(h.detalle) as todos_detalles
    from public.historial h
    where (p_antes is null or h.creado_en < p_antes)
      and (p_qr is null or h.qr_id = p_qr)
      and (p_usuario is null or h.usuario_email = p_usuario)
    group by h.accion, h.usuario_id, h.usuario_email, h.creado_en
    order by h.creado_en desc
    limit least(greatest(coalesce(p_limite, 100), 1), 500)
  )
  select g.accion, g.usuario_email, g.creado_en, g.cantidad, g.desde_qr, g.hasta_qr,
         case when g.cantidad = 1 then g.todos_cambios[1] end,
         (select array_agg(distinct k) from unnest(g.todos_cambios) c, jsonb_object_keys(c) k),
         (select array_agg(distinct d ->> 'diseno') filter (where d ->> 'diseno' is not null)
            from unnest(g.todos_detalles) d),
         g.todos_detalles[1] ->> 'formato'
  from grupos g
  order by g.creado_en desc;
$$;

revoke all on function public.historial_general(integer, timestamptz, bigint, text) from public;
grant execute on function public.historial_general(integer, timestamptz, bigint, text) to authenticated;
